const data = [
  {
    id: "1",
    title: "freeride",
    precio: 300,
    img: "/Imagenes/1.jpg",
    stock: 10,
    category: "ipa",
  },
  {
    id: "2",
    title: "West Coast",
    precio: 300,
    img: "/Imagenes/2.jpg",
    stock: 9,
    category: "ipa",
  },
  {
    id: "3",
    title: "Amber Ale",
    precio: 350,
    img: "/Imagenes/3.jpg",
    stock: 8,
    category: "roja",
  },
  {
    id: "4",
    title: "Blonde Ale",
    precio: 320,
    img: "/Imagenes/4.jpg",
    stock: 7,
    category: "rubia",
  },
  {
    id: "5",
    title: "freeride",
    precio: 300,
    img: "/Imagenes/1.jpg",
    stock: 10,
    category: "ipa",
  },
  {
    id: "6",
    title: "West Coast",
    precio: 300,
    img: "/Imagenes/2.jpg",
    stock: 9,
    category: "ipa",
  },
  {
    id: "7",
    title: "Amber Ale",
    precio: 350,
    img: "/Imagenes/3.jpg",
    stock: 8,
    category: "roja",
  },
  {
    id: "8",
    title: "Blonde Ale",
    precio: 320,
    img: "/Imagenes/4.jpg",
    stock: 7,
    category: "rubia",
  },
];

export { data };
